# permissions for end users to view pdfdocuments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pdfdocument-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pdfcontroller
    app.kubernetes.io/part-of: pdfcontroller
    app.kubernetes.io/managed-by: kustomize
  name: pdfdocument-viewer-role
rules:
- apiGroups:
  - k8s.startkubernetes.com
  resources:
  - pdfdocuments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.startkubernetes.com
  resources:
  - pdfdocuments/status
  verbs:
  - get
